### ISSUE TITLE
Implementación de visualización de playlists

### ISSUE THREAD

**Issue by ferpb** [UNIZAR-30226-2020-02/WebApp#10]

**Comment by PedroPerez14** [comment]
Se recuperan playlists de la BD y queda mostrarlas de varias formas en pantalla, de momento se muestran como scroll horizontal de canciones sueltas,estará bien mostrar una miniatura que represente toda la playlist como en spotify

**Comment by ferpb** [comment]
Las canciones de las playlists ahora se muestran en una pantalla separada, pero hace falta buscar otra manera de recuperar las canciones. Ahora en cada cambio que detecta Angular en la lista repite la función de recuperar canciones.
