### ISSUE TITLE
Almacenar el estado del usuario logeado de forma local

### ISSUE THREAD

**Issue by ferpb** [UNIZAR-30226-2020-02/WebApp#17]

**Comment by PedroPerez14** [comment]
Almacena nombre de usuario de momento. Falta la foto del usuario.

**Comment by PedroPerez14** [comment]
Se almacena nombre de usuario, su correo, si es premium, no premium o creador de contenido, y su foto de perfil. Se recuperan en el momento de hacer login para evitar tener que hacer una petición a la api de la bd cada vez que las queremos recuperar
