### ISSUE TITLE
Pantalla reproductor 

### ISSUE THREAD

**Issue by enrirf** [UNIZAR-30226-2020-02/WebApp#3]

**Comment by PedroPerez14** [comment]
El reproductor funciona pero habrá que añadirle algún botón, y que se pueda saltar de parte de la canción/podcast en streaming porque de momento no deja

**Comment by PedroPerez14** [comment]
Hacer streaming y saltar de punto dentro de la canción es un dolor, hace lo que quiere

**Comment by PedroPerez14** [comment]
Casi está al 100%
