### ISSUE TITLE
Implementación opciones de personalización de perfil de usuario

### ISSUE THREAD

**Issue by ferpb** [UNIZAR-30226-2020-02/WebApp#7]

**Comment by ferpb** [comment]
Está hecho un primer esquema.
Falta conectarse con la base de datos y arreglar los estilos.

**Comment by PedroPerez14** [comment]
Queda hacer que la interfaz conecte con la BD para cambiar los datos

**Comment by PedroPerez14** [comment]
Solo falta para cambiar la foto del perfil, estoy ahora con ello
