### ISSUE TITLE
Implementación del login en la aplicación

### ISSUE THREAD

**Issue by ferpb** [UNIZAR-30226-2020-02/WebApp#8]

**Comment by PedroPerez14** [comment]
Casi está al 100%, hay login pero falta hacerlo persistente, y que si no estás logeado y accedes a alguna página diferente a la del inicio te mande por defecto a la de login, esto lo haré más tarde

**Comment by PedroPerez14** [comment]
Por fin funciona, pero si haces f5 te pide logearte otra vez, no sé hacer autologin así que se queda como está
